on:
  workflow_run:
    workflows: ["E2E tests"]
    types: [completed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v1
        with:
          package-version-ids: ${{ github.event.workflow_run.head_sha }}
